### ISSUE TITLE
Does not work in Windows 11

### ISSUE THREAD

**Issue by thetijle** [Rouble/Hori-FS2#5]
I'm trying to find a version of this driver to work in Windows 11. This has worked the best I have found. They are at least identifying as Flight Stick 2 in the Device Manager, but it still doesn't read an button inputs. Is there anything I can do to make this work on Windows 11?

**Comment by Rouble** [comment]
have you enabled test signed drivers? 
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option

I had a weird quirk where it'd only work if it was plugged into a USB hub and not directly into my computer. That may have just been Windows getting bad versions of the driver linked to the computer's USB ports and not updating them when I recompiled the driver though, so your mileage may vary on trying different ports/hubs.

If you've tried both of the above, I'd try compiling the project on your own system next.

If none of the above works, you're probably out of luck, I never could wrap my head around how the code worked and couldn't find any good resources for learning how to understand it. I also don't have the HOTAS any more and don't have Win 11 to try testing on it.

**Comment by thetijle** [comment]
It was in fact the USB hub that solved the issue.

Thank you for your help, I've been trying to make this happen for literal years!
